// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASzt6PdKGSeoBOMIEfhZev4fy_C2X11Es',
    appId: '1:957072366430:web:fee33234934a91a6664dcf',
    messagingSenderId: '957072366430',
    projectId: 'myregister-b620e',
    authDomain: 'myregister-b620e.firebaseapp.com',
    storageBucket: 'myregister-b620e.firebasestorage.app',
    measurementId: 'G-H5EC941KHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3A2zD-yQjA0zJUCl8bvV2gF-yRf6gPc',
    appId: '1:957072366430:android:45b3399e5b24dbe2664dcf',
    messagingSenderId: '957072366430',
    projectId: 'myregister-b620e',
    storageBucket: 'myregister-b620e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkhp6_0Aj-SFQup-pdY0iygLVVtQnWmOg',
    appId: '1:957072366430:ios:1c2f9f763f342b16664dcf',
    messagingSenderId: '957072366430',
    projectId: 'myregister-b620e',
    storageBucket: 'myregister-b620e.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkhp6_0Aj-SFQup-pdY0iygLVVtQnWmOg',
    appId: '1:957072366430:ios:1c2f9f763f342b16664dcf',
    messagingSenderId: '957072366430',
    projectId: 'myregister-b620e',
    storageBucket: 'myregister-b620e.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASzt6PdKGSeoBOMIEfhZev4fy_C2X11Es',
    appId: '1:957072366430:web:2fdc6239e66d4425664dcf',
    messagingSenderId: '957072366430',
    projectId: 'myregister-b620e',
    authDomain: 'myregister-b620e.firebaseapp.com',
    storageBucket: 'myregister-b620e.firebasestorage.app',
    measurementId: 'G-VTE3BK8XRV',
  );
}
